#!/usr/bin/env python3

import gitlab

token ='XXXXXX'
max_users = 100

gl = gitlab.Gitlab('https://gitlab.cern.ch', private_token=token)
gl.auth()
my_name = gl.user.username
print(my_name)

groups = gl.groups.list()
print(f'number of groups: {len(groups)} ')

# list all the projects
projects = gl.projects.list()
print(f'there are {len(projects)} projects')
for proj in projects:

    n_users = len(proj.members_all.list(per_page=max_users))
    print(f'{proj.name}, users: {n_users}')
    if n_users == max_users and proj.name != 'athena':
        me = proj.members_all.list(search=my_name)[0]
        print(f'will delete {me.name}')
        # me.delete()
